const VALIDATION_ERROR_CODE = 400;
const UNAUTH_CODE = 401;
const NO_MATCH_CODE = 403;
const NOT_FOUND_CODE = 404;
const DUPLICATE_CODE = 409;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  VALIDATION_ERROR_CODE,
  UNAUTH_CODE,
  NO_MATCH_CODE,
  NOT_FOUND_CODE,
  DUPLICATE_CODE,
  DEFAULT_ERROR_CODE,
};