const { Joi, celebrate } = require("celebrate");

module.exports.validateTopicBody = celebrate({
  body: Joi.object().keys({
    topic: Joi.string().required().min(2).max(100).messages({
      "string.min": 'The minimum length of the "topic" field is 2',
      "string.max": 'The maximum length of the "topic" field is 100',
      "string.empty": 'The "topic" field must be filled in',
    }),
    topicResponse: Joi.string().required().min(2).messages({
      "string.min": 'The minimum length of the "topicResponse" field is 2',
      "string.empty":
        'The "topicResponse" field must generated by the OpenAI API',
    }),
    studyTips: Joi.string().required().min(2).messages({
      "string.min": 'The minimum length of the "studyTopics" field is 2',
      "string.empty":
        'The "studyTopics" field must generated at the OpenAI API',
    }),
    _id: Joi.string().required().min(16).messages({
      "string.empty": 'The "_id" field was not sent',
    }),
    color: Joi.string()
      .valid("green", "blue", "yellow", "orange", "red")
      .required()
      .messages({
        "string.empty": "A random color choice was not generated",
      }),
  }),
});

module.exports.validateUserBody = celebrate({
  body: Joi.object().keys({
    username: Joi.string().required().min(2).max(30).messages({
      "string.min": 'The minimum length of the "name" field is 2',
      "string.max": 'The maximum length of the "name" field is 30',
      "string.empty": 'The "name" field must be filled in',
    }),
    email: Joi.string().required().email().messages({
      "string.empty": 'The "email" field must be filled in',
      "string.email": 'The "email" field must be a valid email address',
    }),
    password: Joi.string()
      .required()
      .messages({ "string.empty": 'The "password" field must be filled in' }),
  }),
});

module.exports.validateLoginBody = celebrate({
  body: Joi.object().keys({
    email: Joi.string().required().email().messages({
      "string.empty": 'The "email" field must be filled in',
      "string.email": 'The "email" field must be a valid email address',
    }),
    password: Joi.string()
      .required()
      .messages({ "string.empty": 'The "password" field must be filled in' }),
  }),
});

module.exports.validateID = celebrate({
  params: Joi.object()
    .keys({
      id: Joi.string()
        .required()
        .regex(/^[A-Fa-f0-9]{24}$/),
    })
    .unknown(true),
});
